services:
    #nominatim:
    #    image: mediagis/nominatim:4.4
    #    ports:
    #        - 8080:8080
    #    environment:
    #        - PBF_URL=https://download.geofabrik.de/north-america/canada/ontario-latest.osm.pbf
    jupyter:
        image: jupyter_image
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8888:8888
        volumes:
            - ./models/:/home/jovyan/models
            - ./data:/home/jovyan/data
            - ./notebooks:/home/jovyan/notebooks
        shm_size: 8Gb
          #deploy:
          #  resources:
          #    reservations:
          #      devices:
          #        - driver: nvidia
          #          count: 1
          #          capabilities: [gpu]
